[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
commit_parsers = [
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^docs", group = "📖 Documentation" },
  { message = "^refactor", group = "🔧 Refactor" },
  { message = "^ci", group = "⚙️ CI/CD" },
  { message = "^chore", group = "📦 Miscellaneous" },
]
filter_commits = true
tag_pattern = "v[0-9].*"
